pipeline {
   agent any

   stages {
      stage('checkout') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/saikrishna321/contract-testing-boilerplate']]])
         }
      }
      
      stage('Npm Install') {
         steps {
             sh 'npm install'
        }
      }
      
      stage('Verify Provider  and Publish results to Pact Broker') {
         steps {
             sh 'npm run provider-pact-broker'
        }
      }
   }
   
   
}
